# Generated by Django 5.0 on 2023-12-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(auto_created=True, max_length=10, unique=True),
        ),
    ]
