# Generated by Django 5.0 on 2023-12-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vendor_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(error_messages='Cannot be Changed', max_length=10, unique=True),
        ),
    ]
