# Generated by Django 5.0 on 2024-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teacher_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
